build: false

platform:
  - x64

clone_folder: c:\projects\project-code

cache:
  - c:\ProgramData\chocolatey\bin -> .appveyor.yml
  - c:\ProgramData\chocolatey\lib -> .appveyor.yml

environment:
  global:
    COMPOSER_NO_INTERACTION: 1
    ANSICON: 121x90 (121x90) # Console colors

  ffmpeg_download: https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-5.0-essentials_build.zip

  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.x" # currently 3.8.0
      PYTHON_ARCH: "32"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/fakubeldw67e9pmg/artifacts/YARA.OpenSSL.x86.1.1.1.nupkg"
      VS: "Visual Studio 14 2015"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x" # currently 3.8.0
      PYTHON_ARCH: "64"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/q63539qt9yqaqspo/artifacts/YARA.OpenSSL.x64.1.1.1.nupkg"
      VS: "Visual Studio 14 2015 Win64"

    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9.0"
      PYTHON_ARCH: "32"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/fakubeldw67e9pmg/artifacts/YARA.OpenSSL.x86.1.1.1.nupkg"
      VS: "Visual Studio 14 2015"

    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.0"
      PYTHON_ARCH: "64"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/q63539qt9yqaqspo/artifacts/YARA.OpenSSL.x64.1.1.1.nupkg"
      VS: "Visual Studio 14 2015 Win64"

    - PYTHON: "C:\\Python310"
      PYTHON_VERSION: "3.10.0"
      PYTHON_ARCH: "32"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/fakubeldw67e9pmg/artifacts/YARA.OpenSSL.x86.1.1.1.nupkg"
      VS: "Visual Studio 14 2015"

    - PYTHON: "C:\\Python10-x64"
      PYTHON_VERSION: "3.10.0"
      PYTHON_ARCH: "64"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/q63539qt9yqaqspo/artifacts/YARA.OpenSSL.x64.1.1.1.nupkg"
      VS: "Visual Studio 14 2015 Win64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - pip install -r requirements.txt
  - ps: Start-FileDownload $env:ffmpeg_download

  - 7z x ffmpeg-5.0-essentials_build.zip
  - PATH=%PATH%;%cd%\ffmpeg-5.0-essentials_build\bin

test_script:
  - cd c:\projects\project-code
  - python -m unittest