clone_folder: c:\projects\python-ffmpeg-video-streaming

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    JANSSON_VERSION: "2.13"

  ffmpeg_download: https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-5.0-essentials_build.zip

  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.x" # currently 3.8.0
      PYTHON_ARCH: "32"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/fakubeldw67e9pmg/artifacts/YARA.OpenSSL.x86.1.1.1.nupkg"
      VS: "Visual Studio 14 2015"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x" # currently 3.8.0
      PYTHON_ARCH: "64"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/q63539qt9yqaqspo/artifacts/YARA.OpenSSL.x64.1.1.1.nupkg"
      VS: "Visual Studio 14 2015 Win64"

    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9.0"
      PYTHON_ARCH: "32"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/fakubeldw67e9pmg/artifacts/YARA.OpenSSL.x86.1.1.1.nupkg"
      VS: "Visual Studio 14 2015"

    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.0"
      PYTHON_ARCH: "64"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/q63539qt9yqaqspo/artifacts/YARA.OpenSSL.x64.1.1.1.nupkg"
      VS: "Visual Studio 14 2015 Win64"

    - PYTHON: "C:\\Python310"
      PYTHON_VERSION: "3.10.0"
      PYTHON_ARCH: "32"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/fakubeldw67e9pmg/artifacts/YARA.OpenSSL.x86.1.1.1.nupkg"
      VS: "Visual Studio 14 2015"

    - PYTHON: "C:\\Python10-x64"
      PYTHON_VERSION: "3.10.0"
      PYTHON_ARCH: "64"
      OPENSSL_LIB: "https://ci.appveyor.com/api/buildjobs/q63539qt9yqaqspo/artifacts/YARA.OpenSSL.x64.1.1.1.nupkg"
      VS: "Visual Studio 14 2015 Win64"

install:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "echo %APPVEYOR_BUILD_WORKER_IMAGE%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --disable-pip-version-check --user --upgrade pip"
  - "python -m easy_install -U setuptools"
  - "pip install -r requirements.txt"
  - ps: Start-FileDownload $env:ffmpeg_download

  - 7z x ffmpeg-5.0-essentials_build.zip
  - PATH=%PATH%;%cd%\ffmpeg-5.0-essentials_build\bin

test_script:
  - cd c:\projects\python-ffmpeg-video-streaming
  - python -m unittest